### ISSUE TITLE
Different results in different languages

### ISSUE THREAD

**Issue by gotlium** [jedisct1/siphash-js#3]
Python:

    >>> from siphash import SipHash_2_4

    >>> SipHash_2_4('0123456789ABCDEF', 'a').hash()
    12398370950267227270

    >>> SipHash_2_4('0123456789ABCDEF', '').hash()
    3627314469837380007

Go:

    import "github.com/dchest/siphash"

    h := siphash.New([]byte("0123456789ABCDEF"))
    h.Write([]byte("a"))
    fmt.Println(h.Sum64())
    -- 12398370950267227270

    h := siphash.New([]byte("0123456789ABCDEF"))
    h.Write([]byte(""))
    fmt.Println(h.Sum64())
    -- 3627314469837380007

JS (bug?):

    > SipHash.hash_uint(SipHash.string16_to_key('0123456789ABCDEF'), 'a');
    < 4464775743622278 = $1

    > SipHash.hash_uint(SipHash.string16_to_key('0123456789ABCDEF'), '');
    < 6420369431501223 = $2

**Comment by jedisct1** [comment]
`hash_uint` truncates the output to 53 bits, as JavaScript cannot natively store larger integers.

Python vs JS results, in hex:
```
ac0fdcb09c334c86
   fdcb09c334c86

3256cf4abf4a99a7
  16cf4abf4a99a7
```

**Comment by jedisct1** [comment]
If you need the 64 bit output, use the `hash()` function. The output will be two 32-bit words.
