### ISSUE TITLE
Treats strings as bytes instead of UTF-16 code units?

### ISSUE THREAD

**Issue by JoshuaGrams** [jedisct1/siphash-js#5]
You have:

    function _get_int(a, offset) {
        return a.charCodeAt(offset + 3) << 24 |
               a.charCodeAt(offset + 2) << 16 |
               a.charCodeAt(offset + 1) << 8 |
               a.charCodeAt(offset);
    }
 
But Javascript stores strings as UTF-16, so `charCodeAt` returns a 16-bit code unit. This should give the same results as other implementations for ASCII characters (well, code points 0-127), but otherwise will be weird (will truncate a few bits and add others together). I'm not sure what to do about that: treating strings as UTF-16 data would be easy but would also give different results than other implementations. Translating from UTF-16 to UTF-8 might be more compatible with other implementations but would also be more involved...

So maybe there isn't a good solution, but it seemed like a major caveat so I thought it deserved a mention.

**Comment by jedisct1** [comment]
Messages should really be `Uint8Array`.

I released a new version that treats messages as `Uint8Array` elements, but still converts strings as UTF8 if a `string` is used instead.
